algoritmo "semnome"
// Função :
// Autor :
// Data : 21/06/2022
// Seção de Declarações 
var
idade: inteiro
habilitada: logico
dirigir: logico
inicio
// Seção de Comandos
escreval("Quantos anos vc tem?")
leia(idade)
escreval("A carteira está habilitada? escreva verdadeiro ou falso")
leia(habilitada)

dirigir<- ((idade >= 18) e (habilitada = verdadeiro))
escreval(dirigir)
fimalgoritmo
