algoritmo "Trocar valores"
// Função : Trocar valores
// Autor : Guilherme
// Data : 08/03/2022
// Seção de Declarações 
var
a:inteiro
b:inteiro
c:inteiro

inicio
// Seção de Comandos
a <- 10
b <- 20
escreval("Valores originais das variáveis")
escreval("O valor da variável a é",a)
escreval("O valor da variável b é",b)
c <- a
a <- b
b <- c

escreval("Resultado da Troca de Valores")
escreval("O valor da variável a é",a)
escreva("O valor da variável b é",b)
fimalgoritmo
