algoritmo "semnome"
// Função :
// Autor :
// Data : 20/09/2022
// Seção de Declarações 
var
contador,pessoa,qtd: inteiro
inicio
// Seção de Comandos
para contador de 1 ate 10 faca
     escreval("Digite a idade da pessoa")
     leia(pessoa)
     se pessoa >= 18 entao
        qtd <- qtd + 1
     fimse
fimpara

escreval("A quantidade de pessoas maiores de idade é: ",qtd)
fimalgoritmo
