algoritmo "semnome"
// Função :
// Autor :
// Data : 06/09/2022
// Seção de Declarações 
var
numero,contador,resultado,ant,post: inteiro
inicio
// Seção de Comandos
escreval("Digite um numero")
leia (numero)
post<-1
ant<-0
para contador de 1 ate numero faca
     resultado<- ant + post
     escreval(resultado)
     
ant<-post
post<-resultado
resultado<-contador

fimpara
fimalgoritmo
