algoritmo "semnome"
// Função :
// Autor :
// Data : 02/08/2022
// Seção de Declarações
var
idade: inteiro
altura: real
inicio
// Seção de Comandos
escreval("Escreva sua altura")
leia(altura)

escreval("Escreva sua idade")
leia(idade)

se (idade >= 18) e (altura >= 1.75) entao
   escreval("Parabéns você pode competir")
senao
     escreval("Desculpe, mas infelizmente você não tem o necessário pra competir")
fimse
fimalgoritmo
