algoritmo "MinutosEmHoras"
// Função : tranformar minutos em horas
// Autor :
// Data : 10/05/2022
// Seção de Declarações 
var
horas: inteiro
minutos: real
horario: real
inicio
// Seção de Comandos
escreval("Digite aa horas")
leia(horas)
escreval("Digite os minutos")
leia(minutos)

horario<- minutos / 60 + horas

escreval("O horario em formato de horas é", horario)
fimalgoritmo
